version: '3.5'

volumes:
  #geoserver-data:
  caddy_data: {}

services:
  caddy:
    container_name: caddy
    hostname: oi-dev.com
    entrypoint: ["sh", "-c", "sleep 2073600"]
    image: library/caddy:latest
    env_file: .env
    depends_on:
      - geoserver
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"

  geoserver:
    image: oinf/geoserver:2.16.2
    container_name: gs
    volumes:
      #- geoserver-data:/opt/geoserver/data_dir
      - /root/data_dir:/opt/geoserver/data_dir
      - ${LOCAL_DATA_DIR}:/datadrive
    ports:
      - "8600:8080"
    restart: on-failure
    env_file:
      - docker-env/geoserver.env
      - .env
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
