version: '3.5'

volumes:
   geoserver-data:

services:
   geoserver:
      image: oinf/geoserver:${DOCKER_TAG-2.17.0}
      container_name: gs
      #build:
        #context: ./
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - ${LOCAL_DATA_DIR}:/datadrive
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
        - .env

      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
