version: '3.5'

volumes:
  geoserver-data: {}
  caddy_data: {}

services:
  caddy:
    container_name: caddy
    #hostname: oi-dev.com
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    image: library/caddy:latest
    depends_on:
      - geoserver
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /root/shared:/shared
    ports:
      - "80:80"
      - "443:443"

  geoserver:
    image: oinf/geoserver:${DOCKER_TAG-2.17.0}
    container_name: gs
    environment:
      - STABLE_EXTENSIONS=querylayer-plugin,importer-plugin,monitor-plugin
      - COMMUNITY_EXTENSIONS=gwc-azure-blobstore-plugin,backup-restore-plugin
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - ${LOCAL_DATA_DIR}:/datadrive
    ports:
      - "8600:8080"
    restart: on-failure
    env_file:
      - .env
